In [1]:
import numpy as np

In [2]:
array = np.array([1, 2, 3, 4, 5, 6])
array

array([1, 2, 3, 4, 5, 6])

In [3]:
array_divididos = np.split(array, 3)
array_divididos

[array([1, 2]), array([3, 4]), array([5, 6])]

In [4]:
for i, value in enumerate(array_divididos):
    print(f"Array {i+1} -> {value}")

Array 1 -> [1 2]
Array 2 -> [3 4]
Array 3 -> [5 6]


In [7]:
# Criando um array 1D com temperaturas diárias de um mês
temperaturas = np.array([22, 21, 23, 25, 20, 19, 21,
                        25, 26, 27, 25, 22,
                        20, 18, 19, 20,21,
                        22, 23, 24, 25, 26,
                        27, 28, 29, 30, 29,
                        28, 27, 26, 25, 24])
temperaturas

array([22, 21, 23, 25, 20, 19, 21, 25, 26, 27, 25, 22, 20, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 29, 28, 27, 26, 25, 24])

In [16]:
# Dividindo as temperaturas em 4 semanas
semanas = np.split(temperaturas, 4)
semanas

[array([22, 21, 23, 25, 20, 19, 21, 25]),
 array([26, 27, 25, 22, 20, 18, 19, 20]),
 array([21, 22, 23, 24, 25, 26, 27, 28]),
 array([29, 30, 29, 28, 27, 26, 25, 24])]

In [17]:
for i, value in enumerate(semanas):
    print(f"Semana {i+1} -> {value}")

Semana 1 -> [22 21 23 25 20 19 21 25]
Semana 2 -> [26 27 25 22 20 18 19 20]
Semana 3 -> [21 22 23 24 25 26 27 28]
Semana 4 -> [29 30 29 28 27 26 25 24]


In [18]:
medias_semanas = [np.mean(semana) for semana in semanas]
medias_semanas

[np.float64(22.0), np.float64(22.125), np.float64(24.5), np.float64(27.25)]

In [19]:
for i, value in enumerate(medias_semanas):
    print(f"Média da Semana {i+1}: {value:.2f}°C")

Média da Semana 1: 22.00°C
Média da Semana 2: 22.12°C
Média da Semana 3: 24.50°C
Média da Semana 4: 27.25°C
