In [1]:
import numpy as np

In [2]:
array = np.array([1, 2, 3, 4, 5, 6])
array

array([1, 2, 3, 4, 5, 6])

In [ ]:
soma = np.add(array, 10)
soma

array([11, 12, 13, 14, 15, 16])

In [6]:
subtracao = np.subtract(array, 5)
subtracao

array([-4, -3, -2, -1,  0,  1])

In [9]:
# Multiplicação
produto = np.multiply(array, 2)
produto

array([ 2,  4,  6,  8, 10, 12])

In [10]:
# Divisão
divisao = np.divide(array, 2)
divisao

array([0.5, 1. , 1.5, 2. , 2.5, 3. ])

In [ ]:
# Funções trignométricas
seno = np.sin(array)
seno


array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029])

In [13]:
# Cosseno

cosseno = np.cos(array)
cosseno

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029])

In [14]:
# Funções estatísticas
media = np.mean(array)
media

np.float64(3.5)

In [16]:
# Desvio padrão
desvio_padrao = np.std(array)
desvio_padrao

np.float64(1.707825127659933)

In [17]:
# Funções de comparação
comparacao_maior_que_3 = np.greater(array, 3)
comparacao_maior_que_3

array([False, False, False,  True,  True,  True])

In [18]:
# Combinar Funções
resultado = np.sqrt(array) + np.power(array, 2)
resultado

array([ 2.        ,  5.41421356, 10.73205081, 18.        , 27.23606798,
       38.44948974])

In [19]:
# Funções exponenciais
exponencial = np.exp(array)
exponencial

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 , 403.42879349])

In [20]:
# Logaritmo
logaritmo = np.log(array)
logaritmo

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947])

In [22]:
# Arredondamento
arredondamento = np.round(array / 2)
arredondamento

array([0., 1., 2., 2., 2., 3.])

In [23]:
# Potencia
potencia = np.power(array, 3)
potencia

array([  1,   8,  27,  64, 125, 216])

In [ ]:
soma_array = np.sum(array)
soma_array

array([1, 2, 3, 4, 5, 6])