Copy
* Uma nova cópia do array é criada em memória.
Isso significa que as 2 matrizes (Original e copia) são independentes uma da outra.  

View
* Não é criada em uma nova copia de array na memória. 
A view compartilha os mesmesmos dados que o array original.

In [2]:
import numpy as np

In [3]:
array_original = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) 

In [6]:
# Cópia Rasa (View)
array_view = array_original[1:, 1:]
array_view

array([[5, 6],
       [8, 9]])

In [7]:
array_view[0, 0] = 99
array_view

array([[99,  6],
       [ 8,  9]])

In [8]:
array_original

array([[ 1,  2,  3],
       [ 4, 99,  6],
       [ 7,  8,  9]])

In [9]:
# Cópia Profunda (Copy)
array_copia = array_original.copy()
array_copia

array([[ 1,  2,  3],
       [ 4, 99,  6],
       [ 7,  8,  9]])

In [11]:
array_copia[0, 0] = 100
array_copia

array([[100,   2,   3],
       [  4,  99,   6],
       [  7,   8,   9]])