In [1]:
import numpy as np

In [2]:
# criando dois arrays 1D
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

In [5]:
novo_array = np.concatenate((array1, array2))
novo_array

array([1, 2, 3, 4, 5, 6])

In [6]:
# Criando arrays para nomes e notas
nomes = np.array(['Alice', 'Bob', 'Charlie'])
notas_matematica = np.array([85, 90, 78])
notas_fisica = np.array([88, 76, 95])

In [8]:
# Usando np.vstack para empilhar verticalmente os dados
dados_estudantes = np.vstack((nomes, notas_matematica, notas_fisica))
dados_estudantes

array([['Alice', 'Bob', 'Charlie'],
       ['85', '90', '78'],
       ['88', '76', '95']], dtype='<U21')

In [9]:
# Usando no np.hstack apra empilhar horizontalmente os dados
matriz_notas = np.column_stack((notas_matematica, notas_fisica))
matriz_notas

array([[85, 88],
       [90, 76],
       [78, 95]])

In [10]:
# Adicionando uma nova coluna com a média das notas
media_notas = np.mean(matriz_notas, axis=1)
matriz_final = np.column_stack((matriz_notas, media_notas))
matriz_final

array([[85. , 88. , 86.5],
       [90. , 76. , 83. ],
       [78. , 95. , 86.5]])